### PR TITLE
eliminate an asymmetry in implementing `pure`

### PR DESCRIPTION
**Pull request by danse**

### CODE REVIEW

**Comment by kqr** [comment]
Hi! I actually intentionally left that as `Right` to help with understanding, for readers who are not particularly used to nested monads. Those readers are probably used to seeing `return` mean "wrap in I/O" but not as used to seeing it mean "wrap in Right." Hopefully the way it is, it gives them an idea of which part of the expression deals with which monad.

I hope you take no offense to this rejection!

**Comment by danse** [comment]
No worries! Different people would probably find it easier to understand in different ways. I managed to make `EitherIO` an instance of applicative, but making it an instance of monad was impossible to me, and also looking at the solution i have to say that i don't grasp it fully. I have read somewhere that by writing a monad we take some decisions about how to combine side effects, so i think that the implementation matters here, somehow ... for example i guess that we are deciding to bail out at the first failure, while we could decide to collect different failure codes on the left side, maybe? Not sure, mainly because i am not sure how to read the implementation of `>>=` for `EitherIO`. Anyways, thanks for writing this tutorial, it is pretty great, the best i found about monad transformers! Cheers!

**Comment by kqr** [comment]
We can _not_ collect all possible errors, for a simple reason:

```
(>>=) :: EitherIO e a -> (a -> EitherIO e b) -> EitherIO e b
```

as you can see the `Left` part (the `e`) has to have the same type on both sides, so we can't turn it from a value to a list (which is what we do when we collect many errors).

If the first `EitherIOe a` is a `Left`, we do not have an `a` (because that is the type of the `Right` value) to pass into the function, so we have to create an `EitherIO e b` out of the `EitherIO e a` we already have. The only way we can do that is by returning the `Left` error exactly as it is.

**Comment by danse** [comment]
Thanks for the explanation. When thinking about collecting errors i was imagining something like a `mergeErrors :: String -> String` such that:

```
> mergeErrors "first error" "second error"
"first error, second error"
```

If it is true that `>>=` is about combining side effects, there is probably some behaviour we are defining there, excluding alternatives. Sorry for talking in abstract terms, since i am still not accustomed enough to quickly build examples

**Comment by kqr** [comment]
That would work if you had the signature

```
(>>=) :: EitherIO String a -> (a -> EitherIO String b) -> EitherIO String b
```

or even

```
(>>=) :: Monoid e => EitherIO e a -> (a -> EitherIO e b) -> EitherIO e b
```

but since you know nothing about what kind of `e` you have, you also cannot smash them together! I'm pretty sure the behaviour `>>=` has in my implementation is the only behaviour that type-checks, but you are welcome to try to get different behaviour!

**Pull request closed without merging**
